services:
  - type: web
    name: gtleagues-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1 --bind 0.0.0.0:$PORT
    envVars:
      - key: GT_SEASON_IDS
        value: "19415,19414,19413,19412,19411,19410,19371,19370,19369,19368,19367,19211"
      - key: SCRAPER_INTERVAL_MINUTES
        value: "15"
      - key: WEBHOOK_KEY
        value: "gtscout-webhook-2026"
      - key: SECRET_KEY
        generateValue: true
